package com.wireblend

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {

    /**
     * Array of controller/action combinations which will be skipped from authentication
     * if the controller and action names match. The action value can also be '*' if it
     * encompasses all actions within the controller.
     */
    static nonAuthenticatedActions = [
            [controller: 'registration', action: '*'],
            [controller: 'about', action: 'index']
    ]

    def filters = {
        all(uri: "/**") {
            before = {

                def skipAuth = nonAuthenticatedActions.find {
                    (it.controller == controllerName) &&
                            ((it.action == '*') || (it.action == actionName))
                }

                if(skipAuth)
                    return true

                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
                // Access control by convention.
                accessControl()
            }
        }
    }
}
